import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Timeline } from "~/components/Timeline";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>TwitterClone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Timeline />
      </div>
    </>
  );
};

export default Home;
